### ISSUE TITLE
leaflet filters - same height as map

### ISSUE THREAD

**Issue by giulianoramat** [qgis2web/qgis2web#1079]
First of all thanks to qgis2web Authors.
I would like to ask if and how it is possible to unlock filters scroll bar from base map. 
The goal would be to keep the left part of the window always centered on the basemap even if in presence of a very long list of filters (that remains very long even if reducing to 3 the number of choices visibe in single boxes).
Thanks again for the great job.
![Screenshot 2024-07-03 144746](https://github.com/qgis2web/qgis2web/assets/65484819/f222f53f-6aed-4719-b4d5-6beabaf932dd)

**Comment by andreaordonselli** [comment]
For now, edit the index.html file with the code I show you.
Thank you for reporting the bug, I will fix the problem in the next version.
Greetings.

```css
<style>
html, body, #map {
	width: 100%;
	height: 100%;
	padding: 0;
	margin: 0;
	overflow: hidden;
}
.col9{
	height: 100%!important;
}
.col3{
	height: 100%;
	overflow: auto;
}
</style>
```
