### ISSUE TITLE
editing the popup

### ISSUE THREAD

**Issue by aurelrob01** [qgis2web/qgis2web#1140]
Hi, 

Hi there! 

I'm fairly new to the qgis2web plugin, although I've already got to grips with it. I'm not a developer at all, and I don't know much about coding. I'd like to be able to change the image display properties (I'm displaying 2 images in the popup). Where can I modify the appropriate file? Thanks in advance.

**Comment by aurelrob01** [comment]
Yes, sorry. 

I'm exporting with leaflet. 
The main goal is to, when clicking on a point of my map, display two pictures that are linked in my attribute table. But by default, images are displayed vertically, and i'd like to display them horizontally. I hope my message is way clearer.

**Comment by andreaordonselli** [comment]
qgis2web prende le immagini da te linkate nella tabella attributi e le porta nella cartella di esportazione.
Forse le tue immagini vanno ruotate?
In ogni caso, per capire meglio, ti chiedo di caricare qui uno zip esempio del tuo progetto con anche le foto.
Poi il popup si può aggiustare tramite css.

**Comment by aurelrob01** [comment]
I finally found a solution. It's more like a "do it yourself" solution, but i just added flex option to .image-container. I'm still struggling on how to change the size of the images but I'll find soon. 

I can't share my work, it's an official project for the administration i'm working, sorry.

Thanks for your reply, I didn't expect you'd answer so quickly. And thanks for the amazing work behind this plugin, really a helpfull one ! Cheers !

**Comment by andreaordonselli** [comment]
I am glad that you have made progress.  
Use CSS to modify the size of the image; locate the file resources/qgis2web.css and change this value.

```css
.leaflet-popup-content td img {
    max-height: 60vh;
    max-width: 60vw;
}
```

What is written above means that the maximum width and height of the images cannot exceed 60% of the monitor. You can write whatever you want, even lock the height and width, for example:

```css
 .leaflet-popup-content td img {
    max-height: 60vh;
    max-width: 60vw;
    height: 100px;
    width: 100px;
}
```

or

```css
 .leaflet-popup-content td img {
    max-height: 60vh;
    max-width: 60vw;
    min-height: 100px;
   min- width: 100px;
}
```

In this way, it maintains the maximum width and height rule but also defines a minimum width and height.

If you are doing this for an administration, consider the enhanced version, published [here](https://github.com/andreaordonselli/qgis2o.gis/) and available with a donation.
