### ISSUE TITLE
Popup size - Solution for bug #493

### ISSUE THREAD

**Issue by greyeagle** [qgis2web/qgis2web#532]
Bug #493 was closed without solution. I am sorry I do not really know how to make a pull request since I am fairly new to GitHub. 
Anyway this is my solution and I hope it will help someone:
For **OpenLayers**: 
In the file qgis2web/resources/qgis2web.css change .ol-popup to 
```css
.ol-popup {
    display: none;
    position: absolute;
    background-color: white;
    -moz-box-shadow: 0 1px 4px rgba(0,0,0,0.2);
    -webkit-filter: drop-shadow(0 1px 4px rgba(0,0,0,0.2));
    filter: drop-shadow(0 1px 4px rgba(0,0,0,0.2));
    padding: 15px;
    border-radius: 10px;
    border: 1px solid #cccccc;
    bottom: 12px;
    left: -50px;   
    height: auto;
    width: auto;
    min-width: 100px;     
    overflow: auto;
    max-height: 250px;
}
```
Mind the last two lines that make the popup scrollable and limit the size to something sensible.

For **Leaflet**:
This is somewhat more complicated and involves changes in python:
In the file qgis2web/leafletScriptStrings.py change popFuncsScript to:
```python
def popFuncsScript(table):
    table = table.encode("utf-8")
    _style = {'maxHeight':'250'}
    popFuncs = """
            var popupContent = {table};
            var style = {_style};
            layer.bindPopup(popupContent,style);""".format(table=table, _style=_style)
    return popFuncs
```
Mind setting the **maxHeight** which causes Leaflet to make the popup scrollable and limits it to a reasonable size.
Additionally in qgis2web/leafletFileScripts.py I changed the following css styles to:
```css
.leaflet-container {
    background: #fff;
    padding-right: 10px;
}
.leaflet-popup-content {
    width:auto !important;
    padding-right:10px;
}
```

I hope this will somehow be helpful. I also had tons of attributes and was lost.
